fn main() {
    // messages.rs and entanglement_net.h are pre-generated by running:
    //   cargo run -p entanglement-net-codegen
    // Rebuild if schema changes (user must re-run codegen manually).
    println!("cargo::rerun-if-changed=../schemas/messages.toml");
}
